import type { Question } from "../types";

function randInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function formatDuration(hours: number, minutes: number): string {
  const h = Math.max(0, hours);
  const m = Math.max(0, minutes);
  const hText = `${h} hour${h !== 1 ? "s" : ""}`;
  const mText = `${m} minute${m !== 1 ? "s" : ""}`;

  if (h > 0 && m > 0) return `${hText} ${mText}`;
  if (h > 0) return hText;
  return mText;
}

function shuffle<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export function generateElapsedTimeQuestion(id: number): Question {
  const isNextDay = Math.random() > 0.4; // 60% chance of overnight / next morning problem
  const minuteChoices = [0, 15, 30, 45, 10, 20, 40, 50];

  let startH: number;
  let startM: number;
  let startAmPm: "am" | "pm";
  let endH: number;
  let endM: number;
  let endAmPm: "am" | "pm";
  let promptTimePhrase: string;

  if (isNextDay) {
    // e.g. 3:15 pm to 9:00 am next morning
    startH = randInt(1, 10);
    startM = minuteChoices[randInt(0, minuteChoices.length - 1)];
    startAmPm = "pm";

    endH = randInt(6, 11);
    endM = minuteChoices[randInt(0, minuteChoices.length - 1)];
    endAmPm = "am";

    const startStr = `${startH}:${startM.toString().padStart(2, "0")} pm`;
    const endStr = `${endH}:${endM.toString().padStart(2, "0")} am`;
    promptTimePhrase = `from ${startStr} until ${endStr} the next morning`;
  } else {
    // Same day across noon: e.g. 8:15 am to 2:45 pm
    startH = randInt(7, 10);
    startM = minuteChoices[randInt(0, minuteChoices.length - 1)];
    startAmPm = "am";

    endH = randInt(1, 5);
    endM = minuteChoices[randInt(0, minuteChoices.length - 1)];
    endAmPm = "pm";

    const startStr = `${startH}:${startM.toString().padStart(2, "0")} am`;
    const endStr = `${endH}:${endM.toString().padStart(2, "0")} pm`;
    promptTimePhrase = `from ${startStr} until ${endStr} on the same day`;
  }

  const startH24 = (startH % 12) + (startAmPm === "pm" ? 12 : 0);
  const endH24 = (endH % 12) + (endAmPm === "pm" ? 12 : 0);
  const startTotalMin = startH24 * 60 + startM;
  const endTotalMin = endH24 * 60 + endM;

  const elapsedMin = isNextDay
    ? 1440 - startTotalMin + endTotalMin
    : endTotalMin - startTotalMin;

  const elapsedHours = Math.floor(elapsedMin / 60);
  const elapsedMinutes = elapsedMin % 60;
  const correctAnswerStr = formatDuration(elapsedHours, elapsedMinutes);

  const prompt = `How much time has elapsed ${promptTimePhrase}?`;

  // Distractors based on common childhood misconceptions:
  const distractorsSet = new Set<string>();

  // 1. Off-by-one fencepost counting (counting start hour as 1st hour)
  distractorsSet.add(formatDuration(elapsedHours + 1, elapsedMinutes));
  if (elapsedHours > 1) {
    distractorsSet.add(formatDuration(elapsedHours - 1, elapsedMinutes));
  }

  // 2. Next-day / 12-hour confusion:
  // If next day, kid computes as if it's the same day evening (missing 12 hours)
  if (isNextDay && elapsedHours > 12) {
    distractorsSet.add(formatDuration(elapsedHours - 12, elapsedMinutes));
  } else if (!isNextDay) {
    // Kid incorrectly adds 12 hours thinking day rolled over
    distractorsSet.add(formatDuration(elapsedHours + 12, elapsedMinutes));
  }

  // 3. Flipped minute subtraction without borrowing an hour:
  // e.g. from 3:45 to 9:15, kid sees 15 and 45 and computes 45 - 15 = 30 without decrementing hour
  if (startM !== endM) {
    const flippedDiff = Math.abs(endM - startM);
    distractorsSet.add(formatDuration(elapsedHours + 1, flippedDiff));
    distractorsSet.add(formatDuration(elapsedHours, flippedDiff));
  }

  // 4. Base-100 decimal borrow error (thinks 100 mins in an hour)
  if (endM < startM) {
    const decimalRemainder = (100 - startM + endM) % 60;
    distractorsSet.add(formatDuration(elapsedHours, decimalRemainder));
  }

  // Remove exact correct answer if generated by mistake
  distractorsSet.delete(correctAnswerStr);

  // Guarantee exactly 3 unique distractors (4 options total)
  let fallbackDelta = 30;
  while (distractorsSet.size < 3) {
    const fallbackMin = Math.max(15, elapsedMin + fallbackDelta);
    const candidate = formatDuration(Math.floor(fallbackMin / 60), fallbackMin % 60);
    if (candidate !== correctAnswerStr) {
      distractorsSet.add(candidate);
    }
    fallbackDelta = fallbackDelta > 0 ? -fallbackDelta - 30 : -fallbackDelta + 30;
  }

  const distractorList = Array.from(distractorsSet).slice(0, 3);
  const options = shuffle([correctAnswerStr, ...distractorList]);
  const correctIndex = options.indexOf(correctAnswerStr);

  return {
    id,
    type: "elapsed-time",
    category: "Time & Measurement",
    prompt,
    data: {
      options,
      correctIndex,
      isNextDay,
    },
    correctAnswer: correctIndex,
  };
}
